[pytest]
addopts = --cov=auth_session --cov=dah_api --cov=cli_parser --cov=debtor_data --cov=debtor_notifications --cov=debtor_reports --cov=main --cov-report=term-missing --cov-fail-under=99
testpaths = tests
